builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X 'github.com/xMlex/go-audit-shipper/internal/model.Version={{.Version}}'
      - -X 'github.com/xMlex/go-audit-shipper/internal/model.Commit={{.Commit}}'
      - -X 'github.com/xMlex/go-audit-shipper/internal/model.ShortCommit={{.ShortCommit}}'
      - -X 'github.com/xMlex/go-audit-shipper/internal/model.BuildDate={{.Date}}'
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"